#el uso de operadores aritmeticos
print ('Manejo de Exponentes en Python: \n')
num=4
exp=3
resultado=num**exp
print ('El resultado de la exponenciacion de 4 a la 3a potencia es:',resultado)
print ('\nDivision entera en Python\n')
n1=10
n2=3
resultado=n1//n2
print ('La parte entera de la división de 10/03 es:',resultado)

print ('\n Módulo o residuo de la división\n')
n1=10
n2=2
resultado=n1%n2
print ('El módulo o residuo de la division de 10/3 es:',resultado)